services:
  api:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    image: localhost/gogetssl/api:dev
    container_name: GoGetSslApiDev
    tty: true
    networks:
      - gogetssl
    volumes:
      - ../:/usr/local/gogetssl/src
    environment:
      - TZ=Asia/Tokyo
      - GOPATH=/usr/local/gogetssl
networks:
  gogetssl:
volumes:
  gogetssl:
